inputData: 
  pagesize: 3
  calc:
    cron: 0 * * * * ?
  userkey:
    prefix: userdata-
  userset:
    key: userset
  toplist:
    key: toplist
  
logging:
  config: classpath:logback-dev.xml
spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 100
    pool:
      max-active: 20
      max-idle: 5
      max-wait: 100
      min-idle: 2